apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: wordpressdb
          - name: MYSQL_USER
            value: wordpressuser
          - name: MYSQL_PASSWORD
            value: wordpresspwd
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
