apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_DATABASE: d29yZHByZXNzZGI=
  MYSQL_USER: d29yZHByZXNzdXNlcg==
  MYSQL_PASSWORD: d29yZHByZXNzcHdk
  MYSQL_RANDOM_ROOT_PASSWORD: MQ==