apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.0
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "300m"
        envFrom:
          - configMapRef:
              name: api-configmap
        env:  
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: mysql-secret
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: mysql-secret
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE
                name: mysql-secret
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - "mysql"
